from .offer_bulk__create_update_view import OfferBulkCreateUpdateView
from .active_public_offer_bulk_create_update_view import ActivePublicOfferBulkCreateView
from .favorite_offer_view import FavoriteOffersListView
from .favorite_offer_add_remove_view import FavoriteCreateDeleteView
from .slot_retrieve_update_destroy_view import SlotRetrieveUpdateDestroyView
from .slot_create_view import SlotCreateView
from .offers_list_view import OfferListView
from .offer_detail_view import OfferDetailView
