# Generated by Django 5.1 on 2024-08-30 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivePublicOfferingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Satış Fiyatı')),
                ('demand_collection_start', models.DateField(verbose_name='Talep Toplama Başlangıcı')),
                ('demand_collection_end', models.DateField(verbose_name='Talep Toplama Bitişi')),
                ('lots_to_sell', models.BigIntegerField(verbose_name='Satılacak Lot')),
                ('public_offering_size', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Halka Arz Büyüklüğü')),
                ('distribution_method', models.CharField(choices=[('Bireysele Eşit', 'Bireysele Eşit'), ('Diğer Yöntem', 'Diğer Yöntem')], max_length=50, verbose_name='Dağıtım Yöntemi')),
            ],
        ),
        migrations.CreateModel(
            name='OfferModel',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('logo', models.URLField(blank=True, default='', null=True)),
                ('url', models.URLField(blank=True, default='', null=True)),
                ('chart', models.URLField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
