# Generated by Django 5.1 on 2024-08-30 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivePublicOfferingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('request_start_date', models.DateField()),
                ('request_end_date', models.DateField()),
                ('lots_to_be_sold', models.BigIntegerField()),
                ('ipo_size', models.DecimalField(decimal_places=2, max_digits=15)),
                ('distribution_method', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OfferModel',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('logo', models.URLField(blank=True, default='', null=True)),
                ('url', models.URLField(blank=True, default='', null=True)),
                ('chart', models.URLField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
