# Generated by Django 5.1 on 2024-09-03 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progres_type', models.CharField(choices=[('t_sale', 't_sale'), ('t_1_sale', 't_1_sale'), ('t_2_sale', 't_2_sale'), ('buy', 'buy')], default='buy', max_length=10)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('action_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('action_time',),
            },
        ),
        migrations.CreateModel(
            name='ShareOwnershipModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking', models.BooleanField(default=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.offermodel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('slots', models.ManyToManyField(to='offer.slotmodel')),
            ],
        ),
    ]
