# Generated by Django 5.1 on 2024-09-03 03:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_slotmodel_shareownershipmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShareOwnershipModel',
            new_name='OfferOwnershipModel',
        ),
    ]
