# Generated by Django 5.1 on 2024-09-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0004_favoriteoffermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferPriceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='offermodel',
            name='price_flow',
            field=models.ManyToManyField(blank=True, to='offer.offerpricemodel'),
        ),
    ]
